[package]
name = "tailwindcss-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "4"
html5ever = "*"
markup5ever_rcdom = "0.1.0"
clap = { version = "3.1.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.8.4"
